### ISSUE TITLE
ci: pdm build failed

### ISSUE THREAD

**Issue by YDX-2147483647** [YDX-2147483647/bitroom#2]
```
AttributeError: 'HTTPResponse' object has no attribute 'strict'
```

- https://github.com/YDX-2147483647/bitroom/actions/runs/4884158582/jobs/8717108332
- https://github.com/YDX-2147483647/bitroom/actions/runs/4884158582/jobs/8717108332 `pdm build -v`
- https://github.com/YDX-2147483647/bitroom/actions/runs/4884959185/jobs/8718396348 `pdm self list`

https://github.com/ionrock/cachecontrol/issues/292 
https://github.com/pdm-project/pdm/issues/1879

It's requests 2.30, which allows urllib3 v2.

https://github.com/psf/requests/blob/main/HISTORY.md#2300-2023-05-03

**Comment by YDX-2147483647** [comment]
For others convenience:

```yaml
      - name: Setup pdm
        uses: pdm-project/setup-pdm@v3
        with:
        with:
          python-version: 3.11
          cache: true
        env:
          PDM_DEPS: 'urllib3<2'  # 👈
```

https://github.com/pdm-project/pdm/issues/1879#issuecomment-1533484132
